### ISSUE TITLE
Cannot control more than one M/E

### ISSUE THREAD

**Issue by TomKaltz** [applest/node-applest-atem#12]
The code should be updated to allow control of multiple M/E for larger ATEM switchers.

**Comment by miyukki** [comment]
Hi, Tom! I already recognized this issue. That's so good idea, but I don't have any 2M/E switchers. Would you be able to run the test after I implement it and write a test if you have it?

**Comment by TomKaltz** [comment]
Yes I have a 2 M/E switcher to test with.

Thomas R. Kaltz III

(586) 214-7150 cell
(866) 855-6350 fax

**Comment by miyukki** [comment]
I see. Please take a time.

**Comment by TomKaltz** [comment]
I did not understand your last message.

**Comment by miyukki** [comment]
Please give me a time.

**Comment by miyukki** [comment]
I have a good news for you that I'll get the  2m/e switchers to implement this library soon.
