### ISSUE TITLE
ATEM dead if send command quickly

### ISSUE THREAD

**Issue by sxd1140** [applest/node-applest-atem#24]
If `setInterval` send `atem.changeTransitionPosition(num)` quickly like `15ms` after a few minutes, The ATEM dead.

If  change transition position by hand on the `blackmagic's Broadcast Panel`, the interval is faster than 15ms, but The ATEM is fine.

I don't test other command have same issue.

**Comment by sxd1140** [comment]
Finally I fixed that. It's about reconnect time, If send command while reconnecting, ATEM dead by wrong `_receivePacket` handle logic.

I rewrite `_receivePacket` part. But I can't create pull request because I don't understand `Coffee`.
Sorry about that.

**Comment by PimHaarsma** [comment]
Hello Sxd1140,

Can you send me information what you have changed? So I can apply same changes to my code. It would be helpful for me.

**Comment by sxd1140** [comment]
I read skaarhoj's arduino code port to JS.
https://github.com/kasperskaarhoj/SKAARHOJ-Open-Engineering/tree/master/ArduinoLibs

**Comment by OrionTheGiant** [comment]
@sxd1140 I think I'm running into the same problem. I know this is pretty old at this point but can you give any more detail on what you changed?

**Comment by sxd1140** [comment]
[Hope helps](https://gist.github.com/sxd1140/11117d36baf83f1f621a3661bbc6e5b2)
