### ISSUE TITLE
Reconnect on failure?

### ISSUE THREAD

**Issue by tmanternach** [applest/node-applest-atem#6]
I'm using this library, and it is working great except for one thing. If I lose connection to the switcher, my script just hangs. There is no error, and no attempt to re-connect. Am I missing something simple here? Thank you.

**Comment by miyukki** [comment]
@tmanternach That's sounds good. If you want feature of auto-reconnect, wait a few days because I will implement it.

**Comment by miyukki** [comment]
@tmanternach 
I just published the version of auto-reconnect. Now you can try it :D
https://www.npmjs.com/package/applest-atem

Thanks feedback!

**Comment by tmanternach** [comment]
@miyukki It worked perfect! Thank you very much.
